from http.server import BaseHTTPRequestHandler, HTTPServer

HOST = "0.0.0.0"
PORT = 80


class AppHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        # You can add routing if you want, for now everything hits this.
        self.send_response(200)
        self.send_header("Content-type", "text/html; charset=utf-8")
        self.end_headers()
        self.wfile.write(b"""
        <!DOCTYPE html>
        <html>
          <head>
            <title>PyWeb App</title>
          </head>
          <body>
            <h1>Python Web App on EC2</h1>
            <p>This HTML is generated by <strong>server.py</strong></p>
          </body>
        </html>
        """)


if __name__ == "__main__":
    print("Web server running on port:", PORT)
    httpd = HTTPServer((HOST, PORT), AppHandler)
    httpd.serve_forever()


